### ISSUE TITLE
how to create costume phising scenarios

### ISSUE THREAD

**Issue by christmex** [wifiphisher/extra-phishing-pages#18]
hi guys, i want to create a new scenarios costume, how ? please tell me. thanks for your help !

**Comment by JetseVerschuren** [comment]
The easiest is to copy a existing scene and modifying it.

**Comment by christmex** [comment]
i have do that, and install again, but it's not working dude . how? thanks

**Comment by JetseVerschuren** [comment]
Can you post your files and the command you use to call wifiphisher?

**Comment by christmex** [comment]
send me some email , christmex@yahoo.com . and i send you my files phising page . thanks before

**Comment by christmex** [comment]
hello friend @JetseVerschuren , i send you some email, have you see ?

**Comment by JetseVerschuren** [comment]
I have already replied, maybe check your spam folder if you can't see my mail.

**Comment by christmex** [comment]
okay friend , i see that.

**Comment by brokenhungry** [comment]
you guys wanna share your solutions with everyone else by chance?

**Comment by JetseVerschuren** [comment]
I wouldn't mind sharing but i can't find the mails nor remember what even the problem was.

**Comment by sophron** [comment]
It's not clear what you mean by scenario costume. There are instruction on how to create your own scenario here: https://wifiphisher.readthedocs.io/en/latest/custom_phishing_scenario.html
