### ISSUE TITLE
Load custom phishing page

### ISSUE THREAD

**Issue by nikzebi** [wifiphisher/extra-phishing-pages#21]
Hello, 
I have downloaded the custom phishing pages and set it in the good directory: wifiphisher/data/phishing-pages
The problem now is when I run the programm with a custom phishing page. I receive this message:

```bash
wifiphisher --essid "FREE WI-FI" -p facebook-login
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-01-01 13:55
[*] Happy new year!
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wfphshr-wlan0 interface for creating the rogue Access Point
[+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:aa:26:a9
[+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:92:09:15
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 693, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 534, in start
    self.template_manager)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/tui.py", line 130, in gather_info
    raise phishingpage.InvalidTemplate
wifiphisher.common.phishingpage.InvalidTemplate: The given template is either invalid or not available locally!
```
I don't know how to resolve it. Thanks for your help and sorry for my bad english.

**Comment by blackHatMonkey** [comment]
Hi @nikzebi. Did you install wifiphisher after placing new templates?

**Comment by nikzebi** [comment]
No I first have installed wifiphisher then the templates

**Comment by nikzebi** [comment]
When I do it with the standard template (oauth-login) it works.

**Comment by nikzebi** [comment]
So i need to delete it and to reinstall or just to do an update ?

**Comment by JetseVerschuren** [comment]
Just rerun `sudo python setup.py install`.

**Comment by nikzebi** [comment]
Okey thanks i'm going to test it now and I will say if it works

**Comment by nikzebi** [comment]
IT WORKS THANKS !!

**Comment by xXMASTER276Xx** [comment]
> Just rerun `sudo python setup.py install`.

Thanks, love u.

**Comment by yilianziyu** [comment]
I think I got the same issue:adding a new custom phishing pages directory;putting it into `/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/data/phishing-pages/`;and then running command `wifiphisher -p THE-PAGES-PATH`,getting erro juest like yours:

> wifiphisher.common.phishingpage.InvalidTemplate: The given template is either invalid or not available locally!

I've tried to  run `sudo python setup.py install` ,but it didn't work.It just covered all the phishing pages  I added.Am I miss something?How should I make it all right to adding a new phishing pages?
