### ISSUE TITLE
can't install custom scenarios

### ISSUE THREAD

**Issue by badrshah** [wifiphisher/extra-phishing-pages#23]
so I am using kali live persistence USB. I installed wifiphisher via command line. Now I want to install some custom phishing scenarios but the problem is, I cant seem to find wifiphisher directory anywhere (wifiphisher/data/phishingpages). there's no such folder as 'wifiphisher' to begin with. 
what should I do?

**Comment by Matthuffy** [comment]
Give up!! if you cannot find that then there is no hope for you at all. Go back to collecting stamps

**Comment by badrshah** [comment]
Well son if i knew you'd grow up to be such an insolent bastard I'd never have banged your mum that night. But shit happens huh i mean look at you.

**Comment by sophron** [comment]
@badrshah You can use `whereis` command to find out where Wifiphisher is located.

Both of you, please read our Code of Conduct: https://github.com/wifiphisher/wifiphisher/blob/master/CODE_OF_CONDUCT.md

If you insult any other member again, I will have to ban you from the project.
