### ISSUE TITLE
New and updated pages on my fork

### ISSUE THREAD

**Issue by kleo** [wifiphisher/extra-phishing-pages#32]
It has been a few months since my PRs and still haven't been merged. Feel free to check out https://github.com/kleo/extra-phishing-pages

**Comment by sophron** [comment]
@kleo Thanks for your contributions. These are busy days. I'll review your PRs soon.

**Comment by kleo** [comment]
No thank you sir @sophron. You are an inspiration for us all, thank you for your awesome projects!

**Comment by sophron** [comment]
@kleo thank you for your PRs. I merged them. 

If you are interested, I can give you `write` access to the `extra-phishing-pages` repo to commit your changes directly to master.

**Comment by kleo** [comment]
I'm glad I could help! Yes it would be great to have write permissions.

**Comment by sophron** [comment]
Awesome! I sent you an invite.
